name: teco_team_test
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

flutter_intl:
  enabled: true

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  equatable: ^2.0.3
  dartz: ^0.10.1
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  http: ^0.13.4
  retrofit: ^3.0.1+1

  flutter_bloc: ^8.0.1

  sqfentity: ^2.2.0+5
  sqfentity_gen: ^2.2.0+10

  injectable: ^1.5.3
  get_it: ^7.2.0

  freezed_annotation: ^1.1.0

  location: ^4.3.0
  google_maps_flutter: ^2.1.4
  map_launcher: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  freezed: ^1.1.0
  build_runner: ^2.1.8
  build_verify: ^1.1.0
  injectable_generator: ^1.5.2
  retrofit_generator: ^3.0.1+1
  json_serializable: ^6.1.5


flutter:

  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins_medium.ttf
        - asset: assets/fonts/poppins_regular.ttf
        - asset: assets/fonts/poppins_semi_bold.ttf
        - asset: assets/fonts/poppins_extra_bold.ttf

    - family: Squad_icon
      fonts:
        - asset: assets/fonts/squad_icon.ttf

